# Generated by Django 6.1.1 on 2026-10-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('engine_status', models.CharField(max_length=20)),
                ('state', models.CharField(db_index=True, default='pending', max_length=10)),
                ('analysis', models.JSONField(null=True)),
                ('original', models.JSONField(null=True)),
                ('final_name', models.TextField(blank=True, default='')),
                ('rel_dir', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0)),
                ('header', models.TextField(blank=True, default='')),
                ('extraction', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.JSONField(default=list)),
                ('result_path', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-confidence', 'id'],
            },
        ),
    ]
