# Generated by Django 6.1.1 on 2026-10-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_english_notes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('source_path', 'sha256'), name='one_pending_item_per_file_content'),
        ),
        migrations.AddConstraint(
            model_name='scanjob',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'running')), fields=('state',), name='one_running_scan'),
        ),
    ]
