# Generated by Django 6.1.1 on 2026-10-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0005_item_source_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ignored', 'Ignored'), ('removed', 'Removed')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'approved', 'ignored', 'removed'])), name='item_state_is_known'),
        ),
    ]
