# Generated by Django 6.1.1 on 2026-10-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_item_state_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='state',
            field=models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='running', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='scanjob',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['running', 'done', 'error'])), name='scan_state_is_known'),
        ),
    ]
