# Generated by Django 6.1.1 on 2026-10-05 00:29

import django.db.models.deletion
from django.db import migrations, models


def require_sqlite_with_fts5(apps, schema_editor):
    """This migration builds an FTS5 full-text index, which only SQLite offers (and only if it was compiled with FTS5). Say so
    plainly instead of letting 'migrate' stop on a SQL syntax error that explains nothing."""
    connection = schema_editor.connection
    if connection.vendor != "sqlite":
        raise RuntimeError(f"The full-text search migration requires SQLite (this database is {connection.vendor}): "
                           "docflow is built for a local SQLite file.")
    with connection.cursor() as cursor:
        has_fts5 = cursor.execute("SELECT sqlite_compileoption_used('ENABLE_FTS5')").fetchone()[0]
    if not has_fts5:
        raise RuntimeError("The full-text search migration requires a SQLite built with FTS5 "
                           "(sqlite_compileoption_used('ENABLE_FTS5') is false here).")


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0007_scanjob_state_choices'),
    ]

    operations = [
        migrations.RunPython(require_sqlite_with_fts5, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ItemText',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fulltext', serialize=False, to='triage.item')),
                ('text', models.TextField(blank=True, default='')),
            ],
        ),
        # The full-text index. An "external content" FTS5 table reads the text from triage_itemtext instead of copying it, and
        # the three triggers keep it in step. unicode61 with remove_diacritics 2 makes "electricite" find "électricité".
        migrations.RunSQL(
            sql=[
                ("CREATE VIRTUAL TABLE item_fts USING fts5(text, content='triage_itemtext', content_rowid='item_id', "
                 "tokenize='unicode61 remove_diacritics 2')"),
                ("CREATE TRIGGER item_fts_insert AFTER INSERT ON triage_itemtext BEGIN "
                 "INSERT INTO item_fts(rowid, text) VALUES (new.item_id, new.text); END"),
                ("CREATE TRIGGER item_fts_delete AFTER DELETE ON triage_itemtext BEGIN "
                 "INSERT INTO item_fts(item_fts, rowid, text) VALUES ('delete', old.item_id, old.text); END"),
                ("CREATE TRIGGER item_fts_update AFTER UPDATE OF text ON triage_itemtext BEGIN "
                 "INSERT INTO item_fts(item_fts, rowid, text) VALUES ('delete', old.item_id, old.text); "
                 "INSERT INTO item_fts(rowid, text) VALUES (new.item_id, new.text); END"),
            ],
            reverse_sql=[
                "DROP TRIGGER item_fts_update",
                "DROP TRIGGER item_fts_delete",
                "DROP TRIGGER item_fts_insert",
                "DROP TABLE item_fts",
            ],
        ),
    ]
